language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "stable"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run lint+build+test
